---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: aarch64

trigger:
  branches:
    - master
  event:
    - push

steps:
  - name: docker
    image: plugins/docker
    commands:
    - echo "testing scripts"
    - apk add make git grep
    - ls -lrt /usr/libexec/
    - ls -lrt /usr/lib/
    - ls -lrt /usr/local/lib/
    - ls -lrta $HOME/
    - which grep
    - make all-containers
    - echo "success"
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: zebardy/velero
