---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: aarch64

trigger:
  branches:
    - master
  event:
    - push

steps:
  - name: docker
    volumes:
#    - /var/run/docker.sock:/var/run/docker.sock
    - name: var_run
      path: var/run/host
    image: docker
    privileged: true
    commands:
    - echo "testing scripts"
    - apk add make git grep wget
#    - ls -lrt /usr/libexec/ | grep docker || true
#    - ls -lrt /usr/lib/ | grep docker || true
#    - ls -lrt /usr/local/libexec/ | grep docker || true
#    - ls -lrt /usr/local/lib/ | grep docker || true
#    - ls -lrta $HOME/ | grep docker || true
#    - which docker
#    - docker help
    - mkdir -p /usr/local/libexec/docker/cli-plugins/
    - wget --show-progress=off https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-arm64
    - mv ./buildx-v0.5.1.linux-arm64 /usr/local/libexec/docker/cli-plugins/docker-buildx
    - chmod a+x /usr/local/libexec/docker/cli-plugins/docker-buildx
    - ls -lrt /var/run/host/
    - ls -lrt /var/run/  
    - export DOCKER_HOST=unix:///var/run/host/docker.sock
    - docker help
    - docker version
    - docker buildx inspect
    - make all-containers
    - echo "success"
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: zebardy/velero
volumes:
- name: var_run
  host:
    path: /var/run
