---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: aarch64

trigger:
  branches:
    - master
  event:
    - push

steps:
  - name: docker
    volumes:
    - name: var_run
      path: var/run/host
    image: arm64v8/docker
    privileged: true
    environment: 
      REGISTRY:
        from_secret: docker_registry
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
    commands:
    - echo "testing scripts"
    - apk add make git wget
    - mkdir -p /usr/local/libexec/docker/cli-plugins/
    - wget --show-progress=off https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-arm64
    - mv ./buildx-v0.5.1.linux-arm64 /usr/local/libexec/docker/cli-plugins/docker-buildx
    - chmod a+x /usr/local/libexec/docker/cli-plugins/docker-buildx
    - export DOCKER_HOST=unix:///var/run/host/docker.sock
    - make all-containers REGISTRY=$REGISTRY
    - docker login --password $PASSWORD --username $USERNAME
    - docker push $REGISTRY/velero
    - echo "success"
volumes:
- name: var_run
  host:
    path: /var/run
