---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: aarch64

trigger:
  branches:
    - master
  event:
    - push

steps:
  - name: docker
    image: plugins/docker
    commands:
    - echo "testing scripts"
    - make all-containers
    - echo "success"
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: zebardy/velero
